import { MODULE_KEYS, ModuleKey } from './module-keys';

export const FREE_MODULES: ModuleKey[] = [
  MODULE_KEYS.TIP_CALCULATOR,
  MODULE_KEYS.SIZE_CONVERTER,
  MODULE_KEYS.PLUG_VOLTAGE,
  MODULE_KEYS.EMERGENCY_ESSENTIALS,
];

export const PREMIUM_MODULES: ModuleKey[] = [
  MODULE_KEYS.BUDGET_TRACKER,
  MODULE_KEYS.VAT_REFUND,
  MODULE_KEYS.ATM_EXCHANGE,
  MODULE_KEYS.TIMEZONE_HELPER,
];
